### ISSUE TITLE
처음에 빌드할때

### ISSUE THREAD

**Issue by using1047** [hyunwoongko/kochat#16]
깃으로 다운로드 받고 빌드하니까
아무것도 실행이 안됩니다...ㅠㅠ

어떻게 해야 데모를 실행할 수 있나요?

**Comment by hyunwoongko** [comment]
어떻게 안되는건지 자세히 말씀해주시겠어요?

**Comment by kayla220** [comment]
@using1047  @hyunwoongko  저는 kocaht_config.py 의 BASE에서 device 지정하는 부분을 device : 'cpu'로 변경하여 무조건 'cpu'를 사용하게 하였더니 아무것도 실행되지 않는 상태를 해결할 수 있었습니다. 

하지만 저 또한 챗봇을 서버에서 사용해 볼 수 있었으나 새로 학습을 할때 gpu를 사용하지 못 하는 불편함을 겪고 있습니다. 혹시 이를 해결 할 수 있는 방법이나 제가 알아채지 못한 부분이 있을까요?

**Comment by using1047** [comment]
오 저도 같은 문제 입니다.

2021년 10월 6일 (수) 오전 9:48, Da Eun Kim ***@***.***>님이 작성:

**Comment by kayla220** [comment]
> @using1047  @hyunwoongko  저는 kocaht_config.py 의 BASE에서 device 지정하는 부분을 device : 'cpu'로 변경하여 무조건 'cpu'를 사용하게 하였더니 아무것도 실행되지 않는 상태를 해결할 수 있었습니다. 
> 
> 하지만 저 또한 챗봇을 서버에서 사용해 볼 수 있었으나 새로 학습을 할때 gpu를 사용하지 못 하는 불편함을 겪고 있습니다. 혹시 이를 해결 할 수 있는 방법이나 제가 알아채지 못한 부분이 있을까요? 

저는 서버에 문제가 있었습니다.

**Comment by hyunwoongko** [comment]
에러 메시지를 보여주시겠어요?

**Comment by kayla220** [comment]
> 에러 메시지를 보여주시겠어요?

아 저는 위의 Intent 학습시 발생한 문제가 코드가 아닌 gpu 서버에 문제가 있었고 지금은 해결된 상태입니다! 감사합니다. 

+) js를 해본적이 없어서 main.js에서 ip주소를 변경 하였음에도 반영이 되지 않아 헤메고 있었습니다.  chrome에서 cache를 지우고 반영하니 정상 작동하였습니다.

**Comment by hyunwoongko** [comment]
문제가 지속되면 다시 열어주세요~
