### ISSUE TITLE
demo/data 사용

### ISSUE THREAD

**Issue by KWW94** [hyunwoongko/kochat#20]
안녕하세요, 한국어 대화 모델 연구 및 강의를 위해 
여러 레퍼런스를 찾던중 hyunwoongko님의 kochat을 발견했습니다.

hyunwoongko님의 demo/data에 있는 데이터를 사용하고 싶습니다.
출처와 깃의 주소를 남기고 사용을 해도 될까요?

감사합니다.

**Comment by hyunwoongko** [comment]
네 좋습니다 :)
